# Generated by Django 4.2.1 on 2023-05-25 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_id', models.CharField(max_length=255)),
                ('opening_date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('COP', 'Pesos Colombianos')], max_length=3)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Suspended', 'Suspended')], default='Open', max_length=10)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=16, null=True)),
                ('cvv', models.IntegerField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('sede', models.CharField(choices=[('Barranquilla', 'Barranquilla'), ('Cartagena', 'Cartagena'), ('Santa Marta', 'Santa Marta'), ('Sincelejo', 'Sincelejo'), ('Monteria', 'Monteria')], default='Barranquilla', max_length=20)),
                ('description', models.CharField(max_length=200, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('cuotas', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('card_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=200)),
                ('card_brand', models.CharField(choices=[('VISA', 'Visa'), ('MAST', 'MasterCard'), ('AMEX', 'American Express')], max_length=200)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='transactions.account')),
            ],
        ),
    ]
