# Generated by Django 4.2.1 on 2023-05-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank',
            field=models.CharField(default='WesternBank', max_length=30),
            preserve_default=False,
        ),
    ]
